highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://tudordavid.com
author: Tudor David

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Tudor David's Personal Web Page
name: Tudor David
email: tudor@tudordavid.com
email_full: mailto:tudor@tudordavid.com
website: tudordavid.com
website_full: https://tudordavid.com
github: tudordavid
twitter: tudordavid

tel: +41 78 94 44 277
tel_full: tel:+41789444277
#google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
google_maps: 'https://www.zurich.ibm.com/'
address: IBM Research Zurich Säumerstrasse 4 
postcode: CH-8803
city: Rüschlikon
country: Switzerland
# needed for travis-ci build
exclude: [vendor]
